import { Event, Match, User, BasketballScore, AmericanFootballScore, FootballScore, TennisScore, VolleyballScore, CricketScore, BoxingScore, SwimmingScore, GolfScore } from "@/types";

// Mock Users - all are system admins now, event roles are handled separately
export const mockUsers: User[] = [
  {
    id: "admin1",
    name: "John Admin",
    email: "admin@sportshub.com",
    role: "admin",
  },
  {
    id: "host1",
    name: "Jane Host",
    email: "host@sportshub.com",
    role: "admin",
  },
  {
    id: "player1",
    name: "Sarah Player",
    email: "sarah@example.com",
    role: "admin",
  },
  {
    id: "player2",
    name: "Mike Player",
    email: "mike@example.com",
    role: "admin",
  },
  {
    id: "coach1",
    name: "Lisa Coach",
    email: "lisa@example.com",
    role: "admin",
  },
  {
    id: "part1",
    name: "Tim Participant",
    email: "tim@example.com",
    role: "admin",
  },
  {
    id: "coachTest",
    name: "Test Coach",
    email: "coach.test@example.com",
    role: "admin",
  },
  {
    id: "participantTest",
    name: "Test Participant",
    email: "participant.test@example.com",
    role: "admin",
  },
];

// Mock Events with different sports
export const mockEvents: Event[] = [
  {
    id: "evt1",
    title: "Summer Basketball Championship",
    description: "Annual summer basketball tournament featuring the best teams in the city. Professional-level competition with NBA-style rules.",
    venue: "Central Sports Arena",
    date: "2023-07-15T08:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-05-01T12:00:00Z",
    joinCode: "HOOPS2023",
    sport: "basketball",
  },
  {
    id: "evt2",
    title: "Regional Tennis Open",
    description: "Professional tennis tournament with singles and doubles matches. ATP-style scoring and professional courts.",
    venue: "City Tennis Club",
    date: "2023-06-20T09:00:00Z",
    status: "ongoing",
    createdBy: "admin1",
    createdAt: "2023-04-15T10:30:00Z",
    joinCode: "TENNISOPEN",
    sport: "tennis",
  },
  {
    id: "evt3",
    title: "National Football League Finals",
    description: "Season-ending NFL-style American football championship. Full contact, professional rules and regulations.",
    venue: "National Stadium",
    date: "2023-08-05T16:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-05-10T14:45:00Z",
    joinCode: "NFLFINALS",
    sport: "american-football",
  },
  {
    id: "evt4",
    title: "Beach Volleyball Tournament",
    description: "International beach volleyball competition with teams from around the world. Olympic-style format.",
    venue: "Sunset Beach Courts",
    date: "2023-05-01T10:00:00Z",
    status: "completed",
    createdBy: "admin1",
    createdAt: "2023-03-20T09:15:00Z",
    joinCode: "BEACHVBALL",
    sport: "volleyball",
  },
  {
    id: "evt5",
    title: "Cricket World Cup Qualifiers",
    description: "Twenty20 cricket tournament to qualify for the world championship. Fast-paced, exciting matches.",
    venue: "Metropolitan Cricket Ground",
    date: "2023-09-10T11:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-06-01T08:00:00Z",
    joinCode: "CRICKETWC",
    sport: "cricket",
  },
  {
    id: "evt6",
    title: "Golden Gloves Boxing Championship",
    description: "Amateur boxing championship featuring multiple weight classes. Professional-style scoring and safety protocols.",
    venue: "Downtown Boxing Arena",
    date: "2023-07-25T18:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-05-15T14:30:00Z",
    joinCode: "GOLDGLOVES",
    sport: "boxing",
  },
  {
    id: "evt7",
    title: "Aquatic Masters Swimming Meet",
    description: "Competitive swimming event for all age groups. Multiple stroke categories and distance events.",
    venue: "Olympic Aquatic Center",
    date: "2023-06-30T07:00:00Z",
    status: "ongoing",
    createdBy: "admin1",
    createdAt: "2023-04-20T10:00:00Z",
    joinCode: "SWIMFAST",
    sport: "swimming",
  },
  {
    id: "evt8",
    title: "Pro-Am Golf Tournament",
    description: "18-hole stroke play tournament featuring both amateur and professional golfers. Scenic course with challenging holes.",
    venue: "Riverside Golf Club",
    date: "2023-08-12T06:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-06-05T12:00:00Z",
    joinCode: "GOLFPRO",
    sport: "golf",
  },
  {
    id: "evt9",
    title: "World Cup Football Tournament",
    description: "International football (soccer) competition with teams from around the globe. 90-minute matches with extra time and penalties if needed.",
    venue: "International Football Stadium",
    date: "2023-07-01T14:00:00Z",
    status: "upcoming",
    createdBy: "admin1",
    createdAt: "2023-05-25T16:00:00Z",
    joinCode: "WORLDCUP23",
    sport: "football",
  },
];

// Mock Matches with sport-specific scoring
export const mockMatches: Match[] = [
  {
    id: "match1",
    eventId: "evt1",
    sport: "basketball",
    title: "Quarter Final 1",
    teamA: "Lakers",
    teamB: "Warriors",
    scoreA: 108,
    scoreB: 95,
    detailedScore: {
      teamA: { quarters: [28, 22, 31, 27], totalPoints: 108, fouls: 18, timeouts: 4 } as BasketballScore,
      teamB: { quarters: [24, 28, 20, 23], totalPoints: 95, fouls: 22, timeouts: 6 } as BasketballScore,
    },
    startTime: "2023-07-15T09:00:00Z",
    status: "completed",
    notes: "Intense game with Lakers pulling away in the 3rd quarter.",
  },
  {
    id: "match2",
    eventId: "evt1",
    sport: "basketball",
    title: "Quarter Final 2",
    teamA: "Celtics",
    teamB: "Heat",
    startTime: "2023-07-15T11:00:00Z",
    status: "scheduled",
    notes: "Eastern Conference showdown.",
  },
  {
    id: "match3",
    eventId: "evt2",
    sport: "tennis",
    title: "Men's Singles Semi-Final",
    teamA: "Rafael Nadal",
    teamB: "Novak Djokovic",
    scoreA: "6-4, 3-6, 6-2",
    scoreB: "4-6, 6-3, 2-6",
    detailedScore: {
      teamA: { sets: ["6-4", "3-6", "6-2"], games: [6, 3, 6] } as TennisScore,
      teamB: { sets: ["4-6", "6-3", "2-6"], games: [4, 6, 2] } as TennisScore,
    },
    startTime: "2023-06-20T10:00:00Z",
    endTime: "2023-06-20T12:15:00Z",
    status: "completed",
    notes: "Nadal advances after a thrilling 3-set match.",
  },
  {
    id: "match4",
    eventId: "evt3",
    sport: "american-football",
    title: "Conference Championship",
    teamA: "Eagles",
    teamB: "Cowboys",
    scoreA: 28,
    scoreB: 21,
    detailedScore: {
      teamA: { touchdowns: 4, fieldGoals: 0, safeties: 0, totalPoints: 28, yards: 387 } as AmericanFootballScore,
      teamB: { touchdowns: 3, fieldGoals: 0, safeties: 0, totalPoints: 21, yards: 298 } as AmericanFootballScore,
    },
    startTime: "2023-08-05T16:00:00Z",
    status: "scheduled",
    notes: "NFC Championship game - winner goes to Super Bowl.",
  },
  {
    id: "match5",
    eventId: "evt4",
    sport: "volleyball",
    title: "Women's Final",
    teamA: "Brazil",
    teamB: "USA",
    scoreA: "3",
    scoreB: "1",
    detailedScore: {
      teamA: { sets: [25, 18, 25, 25], totalSets: 3, points: 93 } as VolleyballScore,
      teamB: { sets: [22, 25, 21, 19], totalSets: 1, points: 87 } as VolleyballScore,
    },
    startTime: "2023-05-01T14:00:00Z",
    endTime: "2023-05-01T15:45:00Z",
    status: "completed",
    notes: "Brazil wins 3-1 in sets to claim the championship.",
  },
  {
    id: "match6",
    eventId: "evt5",
    sport: "cricket",
    title: "Qualifier Match 1",
    teamA: "Mumbai Indians",
    teamB: "Chennai Super Kings",
    scoreA: "185/6",
    scoreB: "178/8",
    detailedScore: {
      teamA: { runs: 185, wickets: 6, overs: 20, balls: 0, extras: 12 } as CricketScore,
      teamB: { runs: 178, wickets: 8, overs: 20, balls: 0, extras: 8 } as CricketScore,
    },
    startTime: "2023-09-10T14:00:00Z",
    status: "scheduled",
    notes: "T20 format - 20 overs per side.",
  },
  {
    id: "match7",
    eventId: "evt6",
    sport: "boxing",
    title: "Heavyweight Championship",
    teamA: "Mike Johnson",
    teamB: "David Wilson",
    scoreA: "118",
    scoreB: "110",
    detailedScore: {
      teamA: { rounds: [10, 10, 9, 10, 10, 9, 10, 9, 10, 10, 10, 10], knockdowns: 0, totalPoints: 118, result: "Decision" } as BoxingScore,
      teamB: { rounds: [9, 9, 10, 9, 9, 10, 9, 10, 9, 9, 9, 9], knockdowns: 1, totalPoints: 110, result: "Decision" } as BoxingScore,
    },
    startTime: "2023-07-25T20:00:00Z",
    status: "scheduled",
    notes: "12-round championship bout.",
  },
  {
    id: "match8",
    eventId: "evt7",
    sport: "swimming",
    title: "100m Freestyle Final",
    teamA: "Katie Ledecky",
    teamB: "Sarah Sjöström",
    scoreA: "52.34",
    scoreB: "52.89",
    detailedScore: {
      teamA: { time: "52.34", strokes: 28, lane: 4 } as SwimmingScore,
      teamB: { time: "52.89", strokes: 30, lane: 5 } as SwimmingScore,
    },
    startTime: "2023-06-30T19:00:00Z",
    status: "ongoing",
    notes: "World record pace in the women's 100m freestyle.",
  },
  {
    id: "match9",
    eventId: "evt8",
    sport: "golf",
    title: "Final Round",
    teamA: "Tiger Woods",
    teamB: "Rory McIlroy",
    scoreA: "-12",
    scoreB: "-10",
    detailedScore: {
      teamA: { holes: [4, 3, 5, 4, 3, 4, 5, 3, 4, 4, 3, 5, 4, 3, 4, 4, 3, 4], totalStrokes: 276, par: 288, handicap: 0 } as GolfScore,
      teamB: { holes: [4, 4, 5, 3, 3, 4, 5, 4, 4, 4, 3, 5, 4, 3, 5, 4, 3, 4], totalStrokes: 278, par: 288, handicap: 0 } as GolfScore,
    },
    startTime: "2023-08-12T08:00:00Z",
    status: "scheduled",
    notes: "Final round of the tournament - leaderboard is tight.",
  },
  {
    id: "match10",
    eventId: "evt9",
    sport: "football",
    title: "World Cup Final",
    teamA: "Brazil",
    teamB: "Germany",
    scoreA: 2,
    scoreB: 1,
    detailedScore: {
      teamA: { goals: 2, assists: 3, yellowCards: 1, redCards: 0, possession: 55 } as FootballScore,
      teamB: { goals: 1, assists: 2, yellowCards: 2, redCards: 1, possession: 45 } as FootballScore,
    },
    startTime: "2023-07-01T16:00:00Z",
    status: "scheduled",
    notes: "The ultimate showdown for the World Cup title.",
  },
];
